### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by IvicaTuric** [IvicaTuric/LocationLocker#1]
- [ ] Check if decrypted is empty - return Toast msg, don't change note (stay encrypted)
- [ ] Add save notes to phone storage
- [ ] Copy function to note - on hold save to clipboard + toast
- [ ]
